export const SET_TEMPERAMENT_FILTER = "SET_TEMPERAMENT_FILTER";
export const SET_ORDER_NAME = "SET_ORDER_NAME";
export const SET_PAGE = "SET_PAGE";
export const SET_ORIGIN_FILTER = "SET_ORIGIN_FILTER";
export const SET_ORDER_WEIGHT = "SET_ORDER_WEIGHT";
